version: "3.8"
services:
    nodeserver:
        build:
            context: ./server
        ports:
            - "3001:3001"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
    mongo: 
        build:
            context: ./db
        ports:
            - "27017:27017"
